version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y zlib1g-dev libtiff-dev libjpeg-turbo8-dev
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: make mypy
          name: Type check
      - run:
          command: make test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
